name: personal_portfolio
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  animated_text_kit: ^4.2.2
  bulleted_list: ^0.0.1+0.1a
  dio: ^5.4.3
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  icons_plus: ^5.0.0
  # lottie: ^3.1.1
  preload_page_view: ^0.2.0
  simple_shadow: ^0.3.1
  url_launcher: ^6.2.6
  url_launcher_web: ^2.3.1
  web_smooth_scroll: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  personal_flutter_lints:
    git:
      url: https://github.com/ArunPrakashG/personal_flutter_lints.git
      ref: main

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/

flutter_launcher_icons:
  image_path: "assets/logo.png"
  web:
    generate: true
flutter_native_splash:
  color: "#FCFCFC"
  image: "assets/logo.png"
