name: personal_portfolio
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  animate_do: ^3.3.3
  animated_text_kit: ^4.2.2
  bulleted_list: ^0.0.1+0.1a
  circular_clip_route: ^0.2.0+3
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  flutter_shaders: ^0.1.2
  flutter_svg: ^2.0.10+1
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  icons_plus: ^5.0.0
  lottie: ^3.1.0
  simple_shadow: ^0.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.13
  flutter_test:
    sdk: flutter
  personal_flutter_lints:
    git:
      url: https://github.com/ArunPrakashG/personal_flutter_lints.git
      ref: main

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/

  shaders:
    - shaders/animated_mesh_gradient.frag

flutter_launcher_icons:
  image_path: "assets/logo.png"
  web:
    generate: true
flutter_native_splash:
  color: "#FCFCFC"
  image: "assets/logo.png"
